# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: CI

on:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'  # 12:00, first day of the month

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0} # https://github.com/conda-incubator/setup-miniconda#important
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up conda env ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: pydoas_env.yml
        activate-environment: pydoas-dev
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      run: | 
        conda --version
        conda info --envs
        which python
        python --version
    - name: Run setuptools_scm
      run: python -m setuptools_scm
    - name: Install pydoas
      run: python -m pip install . --no-deps
    - name: Run pytest
      run: pytest test --cov=pydoas/ --cov-report xml
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
    - name: Run example scripts
      run: |
        python scripts/ex1_read_and_plot_example_data.py --show 0 --test 1
        python scripts/ex2_create_new_import_spec.py --show 0 --test 1